### ISSUE TITLE
Doesnt work on Mobile Devices

### ISSUE THREAD

**Issue by MonoAdrian23** [Matze997/BetterBlockPick#2]
I have the Relesed Version of this Plugin but it doe's Nothing.

**Comment by Matze997** [comment]
Hey. It's made for devices which support picking a block. If you have any ideas for implementing mobile support, send it to me!😊

**Comment by MonoAdrian23** [comment]
Oh OK, this is what you can write in Readme.
No one know how this Plugin works.
But thanks for this description.

But i have a little hint for you.

Open Minecraft
Open Settings
Activate Split Controls

Have fun!
This Plugin is very useless 🤣

**Comment by Bruhh1234** [comment]
can you upload a video whats this plugin make ?.

**Comment by Matze997** [comment]
@MonoAdrian23 

I don´t know what´s your problem. To all people I know the description is clear.
If you think the plugin is useless then it´s up to you. For me it´s usefull.


@Bruhh1234 
If I have time I couöd maybe record a video. But I´m not quite sure if it´ll work with my computer :-/

~Matze

**Comment by Bruhh1234** [comment]
no effect by Me ? so i used bluestack an mcpe ?

thx for your time

**Comment by Matze997** [comment]
@Bruhh1234 
I don`t quite know that you want to tell me :-/

**Comment by Bruhh1234** [comment]
I play minecraft on Bluestacks with keyboard and mouse. but i don't have a blockpicker

**Comment by Matze997** [comment]
@Bruhh1234 you have to use the Win10 version. The bluestacks version don't work
